package com.Yujin.onegradefixer.epicmoonmod.gameasset;

import com.Yujin.onegradefixer.epicmoonmod.animations.EMAnimations;
import com.Yujin.onegradefixer.epicmoonmod.comboevents.AmmoCondition;
import com.Yujin.onegradefixer.epicmoonmod.comboevents.SavageTigermarkCondition;
import com.Yujin.onegradefixer.epicmoonmod.comboevents.TigermarkCondition;
import com.Yujin.onegradefixer.epicmoonmod.comboevents.events.*;
import com.Yujin.onegradefixer.epicmoonmod.skill.weapon_innate.TsInnate;
import com.merlin204.avalon.client.CameraShake;
import com.merlin204.avalon.util.AvalonEventUtils;
import com.p1nero.invincible.api.events.BaseEvent;
import com.p1nero.invincible.api.events.TimeStampedEvent;
import com.p1nero.invincible.api.skill.ComboNode;
import com.p1nero.invincible.conditions.*;
import com.p1nero.invincible.skill.ComboBasicAttack;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import yesman.epicfight.api.forgeevent.SkillBuildEvent;
import yesman.epicfight.api.utils.math.ValueModifier;
import yesman.epicfight.client.particle.GroundSlamParticle;
import yesman.epicfight.skill.Skill;

import static com.Yujin.onegradefixer.epicmoonmod.comboevents.events.ReloadEvent.Reload;

@Mod.EventBusSubscriber(
        modid = "epicmoonmod",
        bus = Mod.EventBusSubscriber.Bus.MOD
)

public class tsskill {
    public static Skill tsskill;

    @SubscribeEvent
    public static void BuildSkills(SkillBuildEvent event) {
        SkillBuildEvent.ModRegistryWorker registryWorker = event.createRegistryWorker("epicmoonmod");
        ComboNode root = ComboNode.create();
        ComboNode Dash = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_DASH).setPriority(5).addCondition(new SprintingCondition());
        ComboNode Dashot = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TDASHOT).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(5).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new SprintingCondition()).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.4F));
        ComboNode TDashot = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TDASHOT).setPriority(5).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new SprintingCondition()).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(0.65F,"c")).addTimeEvent(ShootEvent.Shoot(0.4F));
        ComboNode Air = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_AIRSLASH).setPriority(6).addCondition(new JumpCondition());
        ComboNode Airshot = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TAIRSHOT).setDamageMultiplier(ValueModifier.multiplier(0.8F)).setImpactMultiplier(0.8F).setPriority(6).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new JumpCondition()).addCondition(new TigermarkCondition()).addTimeEvent(EffekEvent.Effek(0.4F,"c")).addTimeEvent(ShootEvent.Shoot(0.3F));
        ComboNode TAirshot = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TAIRSHOT).setPriority(6).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new JumpCondition()).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(0.4F,"c")).addTimeEvent(ShootEvent.Shoot(0.3F));
        ComboNode Auto1 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_AUTO1).setPriority(1).setConvertTime(0.1F);
        ComboNode Auto2 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_AUTO2);
        ComboNode Auto3 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_AUTO3);
        ComboNode Shot1 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSHOT1).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(2).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.3F));
        ComboNode Shot2 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSHOT2).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(2).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.4F));
        ComboNode Shot3 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSHOT5).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setPriority(2).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.0F,"c")).addTimeEvent(ShootEvent.Shoot(0.5F));
        ComboNode TShot1 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSHOT1).setPriority(2).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(0.3F,"c")).addTimeEvent(ShootEvent.Shoot(0.3F));
        ComboNode TShot2 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSHOT2).setPriority(2).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(0.4F,"c")).addTimeEvent(ShootEvent.Shoot(0.4F));
        ComboNode TShot4 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSHOT5).setPriority(2).setHurtDamageMultiplier(0.5F).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.0F,"c")).addTimeEvent(ShootEvent.Shoot(0.5F));
        ComboNode Skill = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_SKILL).setPriority(1).setCanBeInterrupt(false).addCondition(new AmmoCondition()).addTimeEvent(Reload(0.8F));
        ComboNode Skill02 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_SKILL2).setPriority(5).setCanBeInterrupt(false).addCondition(new StackCondition(2,2)).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(3.0F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 2", false)).setNotCharge(true);
        ComboNode Skill03 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_SKILL3).setPriority(5).setCanBeInterrupt(false).addCondition(new StackCondition(1,1)).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 1", false)).setNotCharge(true);
        ComboNode Skill04 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_SKILL4).setPriority(5).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).setNotCharge(true);
        ComboNode Skill05 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_SKILL5).setPriority(5).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(EffekEvent.Effek(1.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(1.0F)).setNotCharge(true);
        ComboNode Skill06 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL5).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(5).setCanBeInterrupt(false).addCondition(new StackCondition(3,3)).addCondition(new TigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.35F,"c")).addTimeEvent(ShootEvent.Shoot(1.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 3", false)).setNotCharge(true);
        ComboNode Skill07 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL6).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(2).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(EffekEvent.Effek(0.4F,"c")).addTimeEvent(ShootEvent.Shoot(0.4F)).setNotCharge(true);
        ComboNode Skill08 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL7).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(5).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(EffekEvent.Effek(1.1F,"c")).setNotCharge(true);
        ComboNode Skill09 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL8).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(2).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.1F,"c")).addTimeEvent(ShootEvent.Shoot(0.6F)).setNotCharge(true);
        ComboNode Skill10 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL9).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(2).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.0F,"c")).addTimeEvent(ShootEvent.Shoot(0.5F)).setNotCharge(true);
        ComboNode Skill11 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL10).setDamageMultiplier(ValueModifier.multiplier(0.75F)).setImpactMultiplier(0.75F).setPriority(2).setCanBeInterrupt(false).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritSinEvent.USSE(3.0F)).setNotCharge(true);
        ComboNode TSkill = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL).setPriority(5).setCanBeInterrupt(false).addCondition(new StackCondition(2,2)).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(3.0F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 2", false)).setNotCharge(true);
        ComboNode TSkill2 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL2).setPriority(5).setCanBeInterrupt(false).addCondition(new StackCondition(1,1)).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 1", false)).setNotCharge(true);
        ComboNode TSkill3 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL3).setPriority(5).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).setNotCharge(true);
        ComboNode TSkill4 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL4).setPriority(5).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(EffekEvent.Effek(1.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(1.0F)).setNotCharge(true);
        ComboNode TSkill5 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL5).setPriority(5).setCanBeInterrupt(false).addCondition(new StackCondition(3,3)).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.35F,"c")).addTimeEvent(ShootEvent.Shoot(1.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 3", false)).setNotCharge(true);
        ComboNode TSkill6 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL6).setPriority(2).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(0.4F,"c")).addTimeEvent(ShootEvent.Shoot(0.4F)).setNotCharge(true);
        ComboNode TSkill7 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL7).setPriority(5).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(EffekEvent.Effek(1.1F,"c")).setNotCharge(true);
        ComboNode TSkill8 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL8).setPriority(2).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.1F,"c")).addTimeEvent(ShootEvent.Shoot(0.6F)).setNotCharge(true);
        ComboNode TSkill9 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL9).setPriority(2).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(EffekEvent.Effek(1.0F,"c")).addTimeEvent(ShootEvent.Shoot(0.5F)).setNotCharge(true);
        ComboNode TSkill10 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL10).setPriority(2).setCanBeInterrupt(false).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritSinEvent.USSE(3.0F)).setNotCharge(true);
        ComboNode ESkill = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL).setPriority(1).setCanBeInterrupt(false).addCondition(new StackCondition(2,2)).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(3.0F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 2", false)).setNotCharge(true);
        ComboNode ESkill2 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL2).setPriority(1).setCanBeInterrupt(false).addCondition(new StackCondition(1,1)).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 1", false)).setNotCharge(true);
        ComboNode ESkill3 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL3).setPriority(1).setCanBeInterrupt(false).addTimeEvent(ShootEvent.Shoot(0.1F)).setNotCharge(true);
        ComboNode ESkill4 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL4).setPriority(1).setCanBeInterrupt(false).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(EffekEvent.Effek(1.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(1.0F)).setNotCharge(true);
        ComboNode ESkill5 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL5).setPriority(1).setCanBeInterrupt(false).addCondition(new StackCondition(3,3)).addTimeEvent(EffekEvent.Effek(1.35F,"c")).addTimeEvent(ShootEvent.Shoot(1.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 3", false)).setNotCharge(true);
        ComboNode ESkill6 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL6).setPriority(1).setCanBeInterrupt(false).addTimeEvent(EffekEvent.Effek(0.4F,"c")).addTimeEvent(ShootEvent.Shoot(0.4F)).setNotCharge(true);
        ComboNode ESkill7 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL7).setPriority(1).setCanBeInterrupt(false).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(EffekEvent.Effek(1.1F,"c")).setNotCharge(true);
        ComboNode ESkill8 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL8).setPriority(1).setCanBeInterrupt(false).addTimeEvent(EffekEvent.Effek(1.1F,"c")).addTimeEvent(ShootEvent.Shoot(0.6F)).setNotCharge(true);
        ComboNode ESkill9 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL9).setPriority(1).setCanBeInterrupt(false).addTimeEvent(EffekEvent.Effek(1.0F,"c")).addTimeEvent(ShootEvent.Shoot(0.5F)).setNotCharge(true);
        ComboNode ESkill10 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL10).setPriority(1).setCanBeInterrupt(false).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritSinEvent.USSE(3.0F)).setNotCharge(true);
        ComboNode Skill020 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_SKILL2).setPriority(7).addCondition(new JumpCondition()).setCanBeInterrupt(false).addCondition(new StackCondition(3,3)).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(3.0F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 2", false)).setNotCharge(true);
        ComboNode Skill030 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_SKILL3).setPriority(7).addCondition(new SprintingCondition()).setCanBeInterrupt(false).addCondition(new StackCondition(2,3)).addCondition(new TigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 1", false)).setNotCharge(true);
        ComboNode TSkill0 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL).setPriority(7).addCondition(new JumpCondition()).setCanBeInterrupt(false).addCondition(new StackCondition(3,3)).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(3.0F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 2", false)).setNotCharge(true);
        ComboNode TSkill20 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_TSKILL2).setPriority(7).addCondition(new SprintingCondition()).setCanBeInterrupt(false).addCondition(new StackCondition(2,3)).addCondition(new SavageTigermarkCondition()).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 1", false)).setNotCharge(true);
        ComboNode ESkill0 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL).setPriority(4).setCanBeInterrupt(false).addCondition(new JumpCondition()).addCondition(new StackCondition(3,3)).addTimeEvent(ShootEvent.Shoot(2.7F)).addTimeEvent(EffekEvent.Effek(0.7F,"c")).addTimeEvent(EffekEvent.Effek(1.9F,"c")).addTimeEvent(EffekEvent.Effek(2.7F,"e")).addTimeEvent(EffekEvent.Effek(3.1F,"c")).addTimeEvent(UnrelentingSpiritEvent.USE(3.0F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 2", false)).setNotCharge(true);
        ComboNode ESkill20 = ComboNode.createNode(EMAnimations.TENTAI_SEITOU_ESKILL2).setPriority(4).setCanBeInterrupt(false).addCondition(new SprintingCondition()).addCondition(new StackCondition(2,3)).addTimeEvent(ShootEvent.Shoot(0.1F)).addTimeEvent(TimeStampedEvent.createTimeCommandEvent(0.0F, "invincible consumeStack 1", false)).setNotCharge(true);
        ComboNode BasicAttack = ComboNode.create().addConditionNode(Dash).addConditionNode(Air).addConditionNode(Auto1);
        ComboNode Skills = ComboNode.create().addConditionNode(Skill).addConditionNode(Shot1).addConditionNode(TShot1).addConditionNode(Dashot).addConditionNode(TDashot).addConditionNode(Airshot).addConditionNode(TAirshot);
        ComboNode Skill2 = ComboNode.create().addConditionNode(Skill).addConditionNode(Shot2).addConditionNode(TShot2);
        ComboNode Skill3 = ComboNode.create().addConditionNode(Skill).addConditionNode(Shot3).addConditionNode(TShot4);
        ComboNode SA = ComboNode.create().addConditionNode(Skill02).addConditionNode(Skill03).addConditionNode(TSkill2).addConditionNode(TSkill).addConditionNode(TSkill5).addConditionNode(ESkill).addConditionNode(ESkill2).addConditionNode(ESkill5).addConditionNode(Skill06).addConditionNode(Skill020).addConditionNode(Skill030).addConditionNode(TSkill0).addConditionNode(TSkill20).addConditionNode(ESkill0).addConditionNode(ESkill20);
        ComboNode SA2 = ComboNode.create().addConditionNode(Skill04).addConditionNode(TSkill3).addConditionNode(ESkill3);
        ComboNode SA3 = ComboNode.create().addConditionNode(Skill05).addConditionNode(TSkill4).addConditionNode(ESkill4);
        ComboNode SA4 = ComboNode.create().addConditionNode(Skill07).addConditionNode(TSkill6).addConditionNode(ESkill6);
        ComboNode SA5 = ComboNode.create().addConditionNode(Skill08).addConditionNode(TSkill7).addConditionNode(ESkill7);
        ComboNode SA6 = ComboNode.create().addConditionNode(Skill09).addConditionNode(TSkill8).addConditionNode(ESkill8);
        ComboNode SA7 = ComboNode.create().addConditionNode(Skill10).addConditionNode(TSkill9).addConditionNode(ESkill9);
        ComboNode SA8 = ComboNode.create().addConditionNode(Skill11).addConditionNode(TSkill10).addConditionNode(ESkill10);
        root.key1(BasicAttack);
        root.key3(Skills);
        root.key4(SA);
        Air.key1(Auto2);
        Air.key3(Skill2);
        Air.key4(SA);
        Airshot.key1(Auto2);
        Airshot.key3(Skill2);
        Airshot.key4(SA);
        TAirshot.key1(Auto2);
        TAirshot.key3(Skill2);
        TAirshot.key4(SA);
        Dash.key1(Auto2);
        Dash.key3(Skill2);
        Dash.key4(SA);
        Dashot.key1(Auto2);
        Dashot.key3(Skill2);
        Dashot.key4(SA);
        TDashot.key1(Auto2);
        TDashot.key3(Skill2);
        TDashot.key4(SA);
        Auto1.key1(Auto2);
        Auto1.key3(Skill2);
        Auto1.key4(SA);
        Auto2.key1(Auto3);
        Auto2.key3(Skill3);
        Auto2.key4(SA);
        Auto3.key4(SA);
        Shot1.key1(Auto2);
        Shot1.key3(Skill2);
        Shot1.key4(SA);
        Shot2.key1(Auto3);
        Shot2.key3(Skill3);
        Shot2.key4(SA);
        Shot3.key4(SA);
        TShot1.key1(Auto2);
        TShot1.key3(Skill2);
        TShot1.key4(SA);
        TShot2.key1(Auto3);
        TShot2.key3(Skill3);
        TShot2.key4(SA);
        ESkill2.key1(ESkill3);
        ESkill2.key3(ESkill3);
        ESkill2.key4(ESkill3);
        ESkill3.key1(ESkill4);
        ESkill3.key3(ESkill4);
        ESkill3.key4(ESkill4);
        ESkill5.key1(SA4);
        ESkill5.key3(SA4);
        ESkill5.key4(SA4);
        ESkill6.key1(SA5);
        ESkill6.key3(SA5);
        ESkill6.key4(SA5);
        ESkill7.key1(SA6);
        ESkill7.key3(SA6);
        ESkill7.key4(SA6);
        ESkill8.key1(SA7);
        ESkill8.key3(SA7);
        ESkill8.key4(SA7);
        ESkill9.key1(SA8);
        ESkill9.key3(SA8);
        ESkill9.key4(SA8);
        Skill03.key1(SA2);
        Skill03.key3(SA2);
        Skill03.key4(SA2);
        Skill04.key1(SA3);
        Skill04.key3(SA3);
        Skill04.key4(SA3);
        Skill06.key1(SA4);
        Skill06.key3(SA4);
        Skill06.key4(SA4);
        Skill07.key1(SA5);
        Skill07.key3(SA5);
        Skill07.key4(SA5);
        Skill08.key1(SA6);
        Skill08.key3(SA6);
        Skill08.key4(SA6);
        Skill09.key1(SA7);
        Skill09.key3(SA7);
        Skill09.key4(SA7);
        Skill10.key1(SA8);
        Skill10.key3(SA8);
        Skill10.key4(SA8);
        TSkill2.key1(SA2);
        TSkill2.key3(SA2);
        TSkill2.key4(SA2);
        TSkill3.key1(SA3);
        TSkill3.key3(SA3);
        TSkill3.key4(SA3);
        TSkill5.key1(SA4);
        TSkill5.key3(SA4);
        TSkill5.key4(SA4);
        TSkill6.key1(SA5);
        TSkill6.key3(SA5);
        TSkill6.key4(SA5);
        TSkill7.key1(SA6);
        TSkill7.key3(SA6);
        TSkill7.key4(SA6);
        TSkill8.key1(SA7);
        TSkill8.key3(SA7);
        TSkill8.key4(SA7);
        TSkill9.key1(SA8);
        TSkill9.key3(SA8);
        TSkill9.key4(SA8);
        Skill030.key1(SA2);
        Skill030.key3(SA2);
        Skill030.key4(SA2);
        TSkill20.key1(SA2);
        TSkill20.key3(SA2);
        TSkill20.key4(SA2);
        ESkill20.key1(SA2);
        ESkill20.key3(SA2);
        ESkill20.key4(SA2);
        tsskill = registryWorker.build("tsskill", TsInnate::new, ComboBasicAttack.createComboBasicAttack().setMaxPressTime(1).setReserveTime(9).setCombo(root).setShouldDrawGui(false));
    }
}
