package com.Yujin.onegradefixer.epicmoonmod.animations;

import com.Yujin.onegradefixer.epicmoonmod.sound.EMsounds;
import com.merlin204.avalon.epicfight.animations.AvalonAttackAnimation;
import com.merlin204.avalon.util.AvalonAnimationUtils;
import com.merlin204.avalon.util.AvalonEventUtils;
import net.minecraft.world.InteractionHand;
import net.minecraftforge.eventbus.api.EventPriority;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import yesman.epicfight.api.animation.AnimationManager;
import yesman.epicfight.api.animation.property.AnimationEvent;
import yesman.epicfight.api.animation.property.AnimationProperty;
import yesman.epicfight.api.animation.property.MoveCoordFunctions;
import yesman.epicfight.api.animation.types.EntityState;
import yesman.epicfight.api.animation.types.MovementAnimation;
import yesman.epicfight.api.animation.types.StaticAnimation;
import yesman.epicfight.api.collider.Collider;
import yesman.epicfight.api.collider.OBBCollider;
import yesman.epicfight.api.model.Armature;
import yesman.epicfight.api.utils.AttackResult;
import yesman.epicfight.api.utils.TimePairList;
import yesman.epicfight.gameasset.Armatures;
import yesman.epicfight.gameasset.EpicFightSounds;
import yesman.epicfight.model.armature.HumanoidArmature;
import yesman.epicfight.particle.EpicFightParticles;
import yesman.epicfight.world.damagesource.StunType;;

@Mod.EventBusSubscriber(
        modid = "epicmoonmod",
        bus = Mod.EventBusSubscriber.Bus.MOD
)
public class EMAnimations {
    public static final Armatures.ArmatureAccessor<? extends Armature> ARMATURE = Armatures.ArmatureAccessor.create("epicmoonmod", "tentai_seitou", Armature::new);
    public static AnimationManager.AnimationAccessor<StaticAnimation> TENTAI_SEITOU_IDLE;
    public static AnimationManager.AnimationAccessor<StaticAnimation> TENTAI_SEITOU_GUARD;
    public static AnimationManager.AnimationAccessor<MovementAnimation> TENTAI_SEITOU_WALK;
    public static AnimationManager.AnimationAccessor<MovementAnimation> TENTAI_SEITOU_RUN;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_AUTO1;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_AUTO2;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_AUTO3;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSHOT1;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSHOT2;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSHOT5;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_DASH;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TDASHOT;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_AIRSLASH;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_AIRSHOT;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TAIRSHOT;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_SKILL;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_SKILL2;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_SKILL3;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_SKILL4;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_SKILL5;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL2;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL3;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL4;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL5;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL6;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL7;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL8;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL9;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_TSKILL10;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL2;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL3;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL4;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL5;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL6;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL7;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL8;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL9;
    public static AnimationManager.AnimationAccessor<AvalonAttackAnimation> TENTAI_SEITOU_ESKILL10;
    public static final Collider Pisword = new OBBCollider(0.6, 0.6, 0.6, (double) 0.0F, 0.2, -0.2);


    @SubscribeEvent(
            priority = EventPriority.LOWEST
    )
    public static void registerAnimations(AnimationManager.AnimationRegistryEvent event) {
        event.newBuilder("epicmoonmod",EMAnimations::build);
    }

    public static void build(AnimationManager.AnimationBuilder builder) {
        Armatures.ArmatureAccessor<? extends Armature> armature = Armatures.ArmatureAccessor.create("epicmoonmod", "tentai_seitou", Armature::new);
        TENTAI_SEITOU_IDLE = builder.nextAccessor("biped/tiantui/tentai_seitou_idle", (accessor) -> new StaticAnimation(true, accessor, Armatures.BIPED));
        TENTAI_SEITOU_WALK = builder.nextAccessor("biped/tiantui/tentai_seitou_walk", (accessor) -> new MovementAnimation(true, accessor, Armatures.BIPED));
        TENTAI_SEITOU_RUN = builder.nextAccessor("biped/tiantui/tentai_seitou_run", (accessor) -> new MovementAnimation(true, accessor, Armatures.BIPED));
        TENTAI_SEITOU_GUARD = builder.nextAccessor("biped/tiantui/tentai_seitou_guard", (accessor) -> new StaticAnimation(0.15F, true, accessor, Armatures.BIPED));
        TENTAI_SEITOU_AUTO1 = builder.nextAccessor("biped/tiantui/tentai_seitou_auto1", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(10, 35, 35, InteractionHand.MAIN_HAND, 1.0F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F));
        TENTAI_SEITOU_AUTO2 = builder.nextAccessor("biped/tiantui/tentai_seitou_auto2", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(20, 40, 45, InteractionHand.MAIN_HAND, 1.0F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F));
        TENTAI_SEITOU_AUTO3 = builder.nextAccessor("biped/tiantui/tentai_seitou_auto3", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(25, 35, 65, InteractionHand.MAIN_HAND, 1.0F, 1.1F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null),AvalonAnimationUtils.createSimplePhase(50, 60, 65, InteractionHand.MAIN_HAND, 1.0F, 1.1F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.HOLD).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F));
        TENTAI_SEITOU_TSHOT1 = builder.nextAccessor("biped/tiantui/tentai_seitou_tshot1", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(10, 30, 30, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(20,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.1F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSHOT2 = builder.nextAccessor("biped/tiantui/tentai_seitou_tshot2", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(20, 40, 45, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.15F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSHOT5 = builder.nextAccessor("biped/tiantui/tentai_seitou_tshot5", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(30, 40, 75, InteractionHand.MAIN_HAND, 1.5F, 1.6F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null),AvalonAnimationUtils.createSimplePhase(50, 60, 65, InteractionHand.MAIN_HAND, 1.5F, 1.6F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.HOLD).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(30,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(60,20,1,5,4)));
        TENTAI_SEITOU_DASH = builder.nextAccessor("biped/tiantui/tentai_seitou_dash", (accessor) -> (new AvalonAttackAnimation(0.1F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(34, 40, 45, InteractionHand.MAIN_HAND, 1.2F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F));
        TENTAI_SEITOU_TDASHOT = builder.nextAccessor("biped/tiantui/tentai_seitou_tdashot", (accessor) -> (new AvalonAttackAnimation(0.1F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(34, 40, 45, InteractionHand.MAIN_HAND, 2.2F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(40,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.4F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_AIRSLASH = builder.nextAccessor("biped/tiantui/tentai_seitou_airslash", (accessor) -> (new AvalonAttackAnimation(0.1F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(17, 25, 40, InteractionHand.MAIN_HAND, 1.3F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.ActionAnimationProperty.MOVE_VERTICAL, true).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addProperty(AnimationProperty.ActionAnimationProperty.NO_GRAVITY_TIME, TimePairList.create(new float[]{0.1F, 0.2F})));
        TENTAI_SEITOU_TAIRSHOT = builder.nextAccessor("biped/tiantui/tentai_seitou_tairshot", (accessor) -> (new AvalonAttackAnimation(0.1F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(17, 25, 40, InteractionHand.MAIN_HAND, 2.5F, 2.5F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.ActionAnimationProperty.MOVE_VERTICAL, true).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addProperty(AnimationProperty.ActionAnimationProperty.NO_GRAVITY_TIME, TimePairList.create(new float[]{0.1F, 0.2F})).addEvents(AvalonEventUtils.simpleCameraShake(20,20,2,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.3F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_SKILL = builder.nextAccessor("biped/tiantui/tentai_seitou_skill", (accessor) -> (new AvalonAttackAnimation(0.1F, accessor, armature, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(131, 145, 170, InteractionHand.MAIN_HAND, 1.0F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AnimationEvent.InTimeEvent.create(0.10F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.RELOAD1.get(), 0.25F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_SKILL2 = builder.nextAccessor("biped/tiantui/tentai_seitou_skill2", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(170, 180, 200, InteractionHand.MAIN_HAND, 7.5F, 7.5F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.KNOCKDOWN).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(45, 0, 0, 0, 0, 1.5F, true)).addEvents(AvalonEventUtils.simpleGroundSplit(120, 0, 0, 0, 0, 2, true)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(170, 0, 0, 0, 0, 5, true)).addEvents(AnimationEvent.InTimeEvent.create(0.7F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT3.get(), 1.0F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_SKILL3 = builder.nextAccessor("biped/tiantui/tentai_seitou_skill3", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(60, 70, 80, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(35,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.3F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT2.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_SKILL4 = builder.nextAccessor("biped/tiantui/tentai_seitou_skill4", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(26, 36, 55, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.1F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_SKILL5 = builder.nextAccessor("biped/tiantui/tentai_seitou_skill5", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(55, 70, 80, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(35,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.3F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(170, 180, 200, InteractionHand.MAIN_HAND, 10.0F, 10.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.KNOCKDOWN).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(45, 0, 0, 0, 0, 4, true)).addEvents(AvalonEventUtils.simpleGroundSplit(120, 0, 0, 0, 0, 4, true)).addEvents(AvalonEventUtils.simpleGroundSplit(170, 0, 0, 0, 0, 4, true)).addEvents(AnimationEvent.InTimeEvent.create(0.7F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT3.get(), 1.0F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL2 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill2", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(60, 70, 80, InteractionHand.MAIN_HAND, 2.5F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(35,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.3F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT2.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL3 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill3", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(26, 36, 55, InteractionHand.MAIN_HAND, 2.5F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.1F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL4 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill4", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(55, 70, 80, InteractionHand.MAIN_HAND, 2.5F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(35,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.3F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL5 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill5", (accessor) -> (new AvalonAttackAnimation(0.1F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(80, 86, 90, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(85,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(1.1F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL6 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill6", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(20, 40, 45, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.15F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL7 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill7", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(55, 70, 80, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(35,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.3F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL8 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill8", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(60, 70, 75, InteractionHand.MAIN_HAND, 2.0F, 2.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(70,20,1,5,4)).addEvents(AnimationEvent.InTimeEvent.create(0.05F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT4.get(), 0.75F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_TSKILL9 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill9", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(30, 40, 75, InteractionHand.MAIN_HAND, 1.5F, 1.6F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null),AvalonAnimationUtils.createSimplePhase(55, 65, 75, InteractionHand.MAIN_HAND, 1.5F, 1.6F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.HOLD).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(30,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(60,20,1,5,4)));
        TENTAI_SEITOU_TSKILL10 = builder.nextAccessor("biped/tiantui/tentai_seitou_tskill10", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(170, 180, 200, InteractionHand.MAIN_HAND, 10.0F, 10.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.KNOCKDOWN).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(45, 0, 0, 0, 0, 1.5F, true)).addEvents(AvalonEventUtils.simpleGroundSplit(120, 0, 0, 0, 0, 2, true)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(170, 0, 0, 0, 0, 5, true)).addEvents(AnimationEvent.InTimeEvent.create(0.7F, (entitypatch, self, params) -> {entitypatch.playSound(EMsounds.SHOT3.get(), 1.0F, 0, 0);},AnimationEvent.Side.CLIENT)));
        TENTAI_SEITOU_ESKILL = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(170, 180, 200, InteractionHand.MAIN_HAND, 3.0F, 3.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.KNOCKDOWN).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(45, 0, 0, 0, 0, 4, true)).addEvents(AvalonEventUtils.simpleGroundSplit(120, 0, 0, 0, 0, 4, true)).addEvents(AvalonEventUtils.simpleGroundSplit(170, 0, 0, 0, 0, 4, true)));
        TENTAI_SEITOU_ESKILL2 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill2", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(60, 70, 80, InteractionHand.MAIN_HAND, 1.5F, 1.5F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)));
        TENTAI_SEITOU_ESKILL3 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill3", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(26, 36, 55, InteractionHand.MAIN_HAND, 1.5F, 1.5F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)));
        TENTAI_SEITOU_ESKILL4 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill4", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(55, 70, 80, InteractionHand.MAIN_HAND, 1.5F, 1.5F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(35,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)));
        TENTAI_SEITOU_ESKILL5 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill5", (accessor) -> (new AvalonAttackAnimation(0.1F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(80, 86, 90, InteractionHand.MAIN_HAND, 1.0F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(85,20,1,5,4)));
        TENTAI_SEITOU_ESKILL6 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill6", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(20, 40, 45, InteractionHand.MAIN_HAND, 1.0F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(25,20,1,5,4)));
        TENTAI_SEITOU_ESKILL7 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill7", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(55, 70, 80, InteractionHand.MAIN_HAND, 1.0F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(65,20,1,5,4)));
        TENTAI_SEITOU_ESKILL8 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill8", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(60, 70, 75, InteractionHand.MAIN_HAND, 1.0F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_BEGIN, MoveCoordFunctions.RAW_COORD).addProperty(AnimationProperty.ActionAnimationProperty.COORD_SET_TICK,null).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(70,20,1,5,4)));
        TENTAI_SEITOU_ESKILL9 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill9", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(30, 40, 75, InteractionHand.MAIN_HAND, 0.7F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null),AvalonAnimationUtils.createSimplePhase(55, 65, 75, InteractionHand.MAIN_HAND, 0.7F, 1.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.HOLD).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(30,20,1,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(60,20,1,5,4)));
        TENTAI_SEITOU_ESKILL10 = builder.nextAccessor("biped/tiantui/tentai_seitou_eskill10", (accessor) -> (new AvalonAttackAnimation(0.05F, accessor, Armatures.BIPED, 1.0F, 1.0F, new AvalonAttackAnimation.AvalonPhase[]{AvalonAnimationUtils.createSimplePhase(170, 180, 200, InteractionHand.MAIN_HAND, 3.0F, 3.0F, ((HumanoidArmature) Armatures.BIPED.get()).toolR, (Collider) null)})).addProperty(AnimationProperty.AttackPhaseProperty.PARTICLE, EpicFightParticles.HIT_BLADE).addProperty(AnimationProperty.AttackPhaseProperty.SWING_SOUND, EpicFightSounds.WHOOSH_BIG.get()).addProperty(AnimationProperty.AttackPhaseProperty.STUN_TYPE, StunType.KNOCKDOWN).newTimePair(0.0F, 3.5F).addStateRemoveOld(EntityState.ATTACK_RESULT, (damageSource -> AttackResult.ResultType.BLOCKED)).addProperty(AnimationProperty.StaticAnimationProperty.PLAY_SPEED_MODIFIER, (AnimationProperty.PlaybackSpeedModifier) (dynamicAnimation, livingEntityPatch, v, v1, v2) -> 1.0F).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(45,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(120,20,3,5,4)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(45, 0, 0, 0, 0, 1.5F, true)).addEvents(AvalonEventUtils.simpleGroundSplit(120, 0, 0, 0, 0, 2, true)).addEvents(AvalonEventUtils.simpleCameraShake(170,30,20,5,4)).addEvents(AvalonEventUtils.simpleGroundSplit(170, 0, 0, 0, 0, 5, true)));
    }
}
